### ISSUE TITLE
duckdb fails filtering OSM files due to `Unknown column type for prepare: MAP(VARCHAR, VARCHAR)` error

### ISSUE THREAD

**Issue by cregouby** [duckdb/duckdb-r#137] opened 2024-04-01 22:12 UTC
Hello, 
Trying to use {duckdb} to extract information from OpenStreetMap data files, I hit the issue #61 that prevent filtering of OSM data based on tags. 

# Current behavior
The OSM data files (format `.osm.pbf` ) available through multiple data providers, encode the objects **tags** in a MAP(VARCHAR, VARCHAR) structure in order to store tags as **key : values**

This MAP structure is not recognized by the duckdb-r package and prevent any usage of filter from the database.

Almost all of the openstreetmap map attributes are stored in those tags, making {duckdb} unusable for those dataset.

Note that the rest of the features are correct from st_readosm() : 
``` r
# Reading schema for OSM data files is fine:
dbGetQuery(con, glue_sql("DESCRIBE SELECT * FROM st_readosm({its_example_osm_file});", .con = con) )
#>   column_name                                  column_type null  key default
#> 1        kind ENUM('node', 'way', 'relation', 'changeset')  YES <NA>    <NA>
#> 2          id                                       BIGINT  YES <NA>    <NA>
#> 3        tags                        MAP(VARCHAR, VARCHAR)  YES <NA>    <NA>
#> 4        refs                                     BIGINT[]  YES <NA>    <NA>
#> 5         lat                                       DOUBLE  YES <NA>    <NA>
#> 6         lon                                       DOUBLE  YES <NA>    <NA>
#> 7   ref_roles                                    VARCHAR[]  YES <NA>    <NA>
#> 8   ref_types            ENUM('node', 'way', 'relation')[]  YES <NA>    <NA>
#>   extra
#> 1  <NA>
#> 2  <NA>
#> 3  <NA>
#> 4  <NA>
#> 5  <NA>
#> 6  <NA>
#> 7  <NA>
#> 8  <NA>

# Operations on first column is fine as well:
dbGetQuery(con, glue_sql("SELECT kind, COUNT(*) as total_elements FROM st_readosm({its_example_osm_file}) GROUP BY 1; ", .con = con)) 
#>       kind total_elements
#> 1     node           1678
#> 2      way            294
#> 3 relation             14


```

# ReprEx
``` r
(its_example_osm_file <- system.file("its-example.osm.pbf", package = "osmextract" ))
#> [1] "/usr/lib/R/site-library/osmextract/its-example.osm.pbf"
library(duckdb)
#> Le chargement a nécessité le package : DBI
library(glue)
con <- dbConnect(drv = duckdb())
dbExecute(con, "INSTALL spatial; LOAD spatial;")
#> [1] 0

# Issue occurs when interacting with tags column:
dbGetQuery(con, glue_sql("SELECT * FROM st_readosm({its_example_osm_file}) WHERE tags IS NOT NULL; ", .con = con)) 
#> Error: rapi_prepare: Unknown column type for prepare: MAP(VARCHAR, VARCHAR)
```

<sup>Created on 2024-04-02 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment] 2024-04-04 11:55
Thanks. What happens if you do `SELECT * EXCLUDE (tags)` ?

**Comment by cregouby** [comment] 2024-04-04 21:10
Hello @krlmlr,

Excluding (tags) works fine : 
``` r
(its_example_osm_file <- system.file("its-example.osm.pbf", package = "osmextract" ))
#> [1] "/usr/lib/R/site-library/osmextract/its-example.osm.pbf"
library(duckdb)
#> Le chargement a nécessité le package : DBI
library(glue)
con <- dbConnect(drv = duckdb())
dbExecute(con, "INSTALL spatial; LOAD spatial;")
#> [1] 0

# No issue when excluding tags column:
dbGetQuery(con, glue_sql("SELECT * EXCLUDE (tags) FROM st_readosm({its_example_osm_file}) LIMIT 10; ", .con = con)) 
#>    kind       id refs      lat       lon ref_roles ref_types
#> 1  node 21069417 NULL 53.80920 -1.553222      NULL      NULL
#> 2  node 21069418 NULL 53.80860 -1.552508      NULL      NULL
#> 3  node 21069419 NULL 53.80822 -1.552227      NULL      NULL
#> 4  node 21069420 NULL 53.80783 -1.552101      NULL      NULL
#> 5  node 21069421 NULL 53.80730 -1.551771      NULL      NULL
#> 6  node 21093230 NULL 53.81002 -1.565830      NULL      NULL
#> 7  node 21545937 NULL 53.80853 -1.551728      NULL      NULL
#> 8  node 21545938 NULL 53.80809 -1.550785      NULL      NULL
#> 9  node 21545939 NULL 53.80699 -1.548899      NULL      NULL
#> 10 node 26653383 NULL 53.81102 -1.561004      NULL      NULL
```

<sup>Created on 2024-04-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

The thing is the most interesting information (in my own use-case) is within tags...So I can't exclude tags...

**Comment by krlmlr** [comment] 2024-04-05 13:03
Can you use SQL to unnest the data in the column, until this is fully supported here?

**Comment by cregouby** [comment] 2024-04-07 09:31
Hello, 

Duckdb-r Unnest with SQL fails here as we hit the UNNEST typeId validation error: https://github.com/duckdb/duckdb-r/blob/8567ad24642683e34cc1cf3bac6c52b4d181535e/src/duckdb/src/planner/binder/expression/bind_unnest_expression.cpp#L125-L133

Here is the reprex:

``` r
(its_example_osm_file <- system.file("its-example.osm.pbf", package = "osmextract" ))
#> [1] "/usr/lib/R/site-library/osmextract/its-example.osm.pbf"
library(duckdb)
#> Le chargement a nécessité le package : DBI
library(glue)
con <- dbConnect(drv = duckdb())
dbExecute(con, "INSTALL spatial; LOAD spatial;")
#> [1] 0

# unnest tag column
dbGetQuery(con, glue_sql("SELECT unnest(tags) FROM st_readosm({its_example_osm_file});;", .con = con))
#> Error: rapi_prepare: Failed to prepare query SELECT unnest(tags) FROM st_readosm('/usr/lib/R/site-library/osmextract/its-example.osm.pbf');;
#> Error: Binder Error: UNNEST() can only be applied to lists, structs and NULL
#> LINE 1: SELECT unnest(tags) FROM st_readosm('/usr/lib/...
#>                ^
```

<sup>Created on 2024-04-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment] 2024-04-07 09:45
Thanks. Not sure `UNNEST()` can be applied directly to a map. Do you need to work with `map_keys()` and `map_values()` first, or perhaps with `element_at()` ?

https://duckdb.org/docs/sql/functions/nested#map_keysmap

This error is no longer specific to the R package, though.

**Comment by cregouby** [comment] 2024-04-17 17:17
Hello, 
Either `map_keys(tags)` or `map_values(tags)` fails due to the column type.
``` r
Erreur : rapi_prepare: Unknown column type for prepare: MAP(VARCHAR, VARCHAR)
```
here is the reprex :
``` r
(its_example_osm_file <- system.file("its-example.osm.pbf", package = "osmextract" ))
#> [1] "/usr/lib/R/site-library/osmextract/its-example.osm.pbf"
library(duckdb)
#> Le chargement a nécessité le package : DBI
library(glue)
con <- dbConnect(drv = duckdb())
dbExecute(con, "INSTALL spatial; LOAD spatial;")
#> [1] 0

# unnest tag column requires map and map_keys https://duckdb.org/docs/sql/functions/nested#map_keysmap
dbGetQuery(con, glue_sql("SELECT id, tags FROM st_readosm({its_example_osm_file}) WHERE list_contains(map_keys(tags), 'landuse');", .con = con))
#> Error: rapi_prepare: Unknown column type for prepare: MAP(VARCHAR, VARCHAR)
```

<sup>Created on 2024-04-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by krlmlr** [comment] 2024-04-24 06:39
Thanks. This is the inclusion of `tags` in the list of columns. Extracting `map_values(tags)` works.

For reference, Arrow converts dictionaries to two-column data frames, this is what we should do here too.

``` r
(its_example_osm_file <- system.file("its-example.osm.pbf", package = "osmextract"))
#> [1] "/Users/kirill/Library/R/arm64/4.3/library/osmextract/its-example.osm.pbf"
library(duckdb)
#> Loading required package: DBI
library(glue)
con <- dbConnect(drv = duckdb())
dbExecute(con, "INSTALL spatial; LOAD spatial;")
#> [1] 0

# unnest tag column requires map and map_keys https://duckdb.org/docs/sql/functions/nested#map_keysmap
sql <- glue_sql("SELECT id, map_values(tags) FROM st_readosm({its_example_osm_file}) WHERE list_contains(map_keys(tags), 'landuse');", .con = con)
out <- dbGetQuery(con, sql)
tibble::as_tibble(out)
#> # A tibble: 11 × 2
#>           id `map_values(tags)`
#>        <dbl> <list>            
#>  1  23008692 <chr [2]>         
#>  2  26376161 <chr [1]>         
#>  3  26377645 <chr [4]>         
#>  4  38427735 <chr [2]>         
#>  5  84842209 <chr [1]>         
#>  6 142813963 <chr [1]>         
#>  7 142814174 <chr [1]>         
#>  8 160471792 <chr [2]>         
#>  9 297984252 <chr [1]>         
#> 10 562763260 <chr [1]>         
#> 11 609718995 <chr [1]>

copy_sql <- glue_sql("COPY (SELECT * FROM st_readosm({its_example_osm_file}) WHERE list_contains(map_keys(tags), 'landuse')) TO 'osm.parquet';", .con = con)
dbExecute(con, copy_sql)
#> [1] 11

parquet <- arrow::read_parquet("osm.parquet")
parquet[1:3, ]
#> # A tibble: 3 × 8
#>   kind        id                    tags    refs   lat   lon ref_roles ref_types
#>   <chr>    <int> <list<
#>   tbl_df<
#>     key> <list<> <dbl> <dbl> <list<ch> <list<ch>
#> 1 way   23008692                 [2 × 2]    [23]    NA    NA                    
#> 2 way   26376161                 [1 × 2]     [8]    NA    NA                    
#> 3 way   26377645                 [4 × 2]     [5]    NA    NA
parquet$tags[1:3]
#> <list<
#>   tbl_df<
#>     key  : character
#>     value: character
#>   >
#> >[3]>
#> [[1]]
#> # A tibble: 2 × 2
#>   key     value 
#>   <chr>   <chr> 
#> 1 landuse grass 
#> 2 source  survey
#> 
#> [[2]]
#> # A tibble: 1 × 2
#>   key     value
#>   <chr>   <chr>
#> 1 landuse grass
#> 
#> [[3]]
#> # A tibble: 4 × 2
#>   key      value        
#>   <chr>    <chr>        
#> 1 building terrace      
#> 2 landuse  residential  
#> 3 name     Eldon Terrace
#> 4 source   Bing;survey
```

<sup>Created on 2024-04-24 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Side note: The headers for list-of-data-frame columns look odd, see the output of `parquet[1:3, ]` in the example above. I suspect we need to work around in pillar.

**Comment by krlmlr** [comment] 2024-04-24 07:17
Closing as a duplicate of #61, which is much more general than this.

**Closed by krlmlr** 2024-04-24 07:17 UTC

**Comment by cregouby** [comment] 2024-04-24 16:57
That's a fantastic solution ! Thanks a lot !
