### ISSUE TITLE
Can't install extensions on Ubuntu because of version mismatch

### ISSUE THREAD

**Issue by fmichonneau** [duckdb/duckdb-r#623] opened 2024-12-03 09:52 UTC
With the duckdb package version 1.1.3, on Ubuntu 24.10 I see:

``` r
library(duckdb)
#> Loading required package: DBI
con <- dbConnect(duckdb())
dbExecute(con, "INSTALL spatial;")
#> Error in `duckdb_result()`:
#> ! rapi_execute: Failed to run query
#> Error: IO Error: Failed to install 'spatial'
#> The file was built for DuckDB version 'v1.1.3', but we can only load extensions built for DuckDB version '19864453f7'.
dbGetQuery(con, "PRAGMA version;")
#>   library_version  source_id
#> 1   v1.1.3-dev165 19864453f7
```

<sup>Created on 2024-12-03 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

This doesn't happen with the duckdb cli:

```
 duckdb
v1.1.3 19864453f7
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
D pragma version;
┌─────────────────┬────────────┐
│ library_version │ source_id  │
│     varchar     │  varchar   │
├─────────────────┼────────────┤
│ v1.1.3          │ 19864453f7 │
└─────────────────┴────────────┘
```

With the R package, it seems like the extension installer is picking up the `source_id` instead of the version number. I am just guessing, but I'm wondering if it's because the [duckdb version](https://github.com/search?q=repo%3Aduckdb%2Fduckdb-r%20dev165&type=code) bundled with the R package has the `dev165` suffix?

**Comment by fmichonneau** [comment] 2024-12-03 10:19
Update: I cloned the repository locally and removed the `dev165` suffix from https://github.com/duckdb/duckdb-r/blob/54bcf51832556048c290dc205531308eda0602ae/src/duckdb/src/function/table/version/pragma_version.cpp#L2 (lines 2 and 11).

After reinstalling the package from these local files, the extension can be installed.

**Comment by kent37** [comment] 2024-12-03 13:16
I have the same error on MacOS.

**Comment by kent37** [comment] 2024-12-03 16:33
And the same fix works for me.

**Comment by krlmlr** [comment] 2024-12-04 07:07
Thanks, good catch. I can push duckdb 1.1.3-1 soon.

**Comment by krlmlr** [comment] 2024-12-04 12:55
Done in 5502a909bbb8b6448660f32f1a3d6c311239e668.

**Comment by eitsupi** [comment] 2024-12-04 13:00
Shouldn't the release version be tested on CI for extension installation to prevent regression?

**Comment by krlmlr** [comment] 2024-12-04 13:10
Good catch, adding infrastructure for this.

**Comment by gustavdelius** [comment] 2024-12-13 11:13
Just wanted to report that the issue seems to persist in version 1.1.3-1. 

<error/rlang_error>
Error in `duckdb_result()`:
! rapi_execute: Failed to run query
Error: HTTP Error: Failed to download extension "httpfs" at URL "http://nightly-extensions.duckdb.org/v1.1.3/linux_amd64/httpfs.duckdb_extension.gz" (HTTP 403)
Extension "httpfs" is an existing extension.
---
Backtrace:
     ▆
  1. ├─dplyr::select(...)
  2. ├─rfishbase::species(sp$latin_name[missing])
  3. │ ├─fb_tbl(endpt, server, version) %>% fix_ids()
  4. │ └─rfishbase::fb_tbl(endpt, server, version)
  5. │   └─duckdbfs::open_dataset(urls[tbl])
  6. │     └─duckdbfs:::parse_uri(sources, conn = conn, recursive = recursive)
  7. │       └─duckdbfs:::load_httpfs(conn)
  8. │         ├─DBI::dbExecute(conn, paste0("INSTALL 'httpfs'", source, ";"))
  9. │         └─DBI::dbExecute(conn, paste0("INSTALL 'httpfs'", source, ";"))
 10. │           ├─DBI::dbSendStatement(conn, statement, ...)
 11. │           └─DBI::dbSendStatement(conn, statement, ...)
 12. │             ├─DBI::dbSendQuery(conn, statement, ...)
 13. │             └─duckdb::dbSendQuery(conn, statement, ...)
 14. │               └─duckdb (local) .local(conn, statement, ...)
 15. │                 └─duckdb:::duckdb_result(connection = conn, stmt_lst = stmt_lst, arrow = arrow)
 16. └─rfishbase:::fix_ids(.)
 17.   ├─"Speccode" %in% colnames(full_data)
 18.   └─base::colnames(full_data)
 19.     └─base::is.data.frame(x)
Run rlang::last_trace(drop = FALSE) to see 14 hidden frames.

**Comment by krlmlr** [comment] 2024-12-16 06:41
Thanks, weird. I really wonder why this is taking the extension from the "nightly". I double-checked, the duckdb code is set to v1.1.3 . @Tmonster: any idea?

**Comment by gustavdelius** [comment] 2024-12-16 11:15
I am sorry. It turns out to be a problem with the `duckdbfs` package, not with `duckdb` itself. I have now reposted at https://github.com/cboettig/duckdbfs/issues/29 and you can close this issue.

**Closed** 2024-12-31 20:44 UTC
