### ISSUE TITLE
Segfault when creating persistent database

### ISSUE THREAD

**Issue by lboller-pwbm** [duckdb/duckdb-r#115] opened 2024-03-20 21:46 UTC
I downloaded the latest version (0.10) and tried to create a persistent database as follows:

```r
duckdb::dbConnect(
  duckdb::duckdb(),
  dbdir = "temp.duckdb"
)
```

This results in the following error:

```
 *** caught segfault ***
address 0x5631cd3af05d, cause 'memory not mapped'
```

The prior version (0.9.2.-1) works fine.

I am using WSL and R version 4.3.2.

**Comment by krlmlr** [comment] 2024-03-21 05:57
@Antonov548: Can you please take a look?

**Comment by Antonov548** [comment] 2024-03-21 17:29
The problem is in the filename. `temp` name for database is reserved and it's not handled properlly in the version 0.10. It was fixed in https://github.com/duckdb/duckdb-r/commit/a125e4561e29bc1f9aa114e73995a4c1f3c75788

On the main issues is fixed.

**Comment by krlmlr** [comment] 2024-03-22 07:36
Thanks!

@lboller-pwbm: Can you confirm? You can get a Windows binary for the dev version from https://duckdb.r-universe.dev/duckdb# .

**Comment by lboller-pwbm** [comment] 2024-03-22 14:06
Confirmed - dev version fixes it (it's an Ubuntu VM in Windows, so I used that binary).

Thanks!

**Closed** 2024-03-22 16:43 UTC
