### ISSUE TITLE
Error: rapi_prepare: Unknown column type for prepare: MAP(BLOB, BLOB) when using parquet_metadata with dbGetQuery

### ISSUE THREAD

**Issue by nbc** [duckdb/duckdb-r#139] opened 2024-04-05 13:23 UTC
When I try to get parquet_metadata with dbGetQuery I get the error Error: rapi_prepare: Unknown column type for prepare: MAP(BLOB, BLOB)

```
> con <- DBI::dbConnect(duckdb::duckdb())
> tibble::tibble(col1 = c(1,2)) |> arrow::write_parquet("a.parquet")
> 
> DBI::dbGetQuery(con, "FROM parquet_metadata('a.parquet')")
Error: rapi_prepare: Unknown column type for prepare: MAP(BLOB, BLOB)
```
If I exclude the column key_value_metadata it works :

```
> DBI::dbGetQuery(con, "SELECT * EXCLUDE (key_value_metadata) FROM parquet_metadata('a.parquet')")
  file_name row_group_id row_group_num_rows row_group_num_columns row_group_bytes column_id file_offset num_values path_in_schema   type stats_min stats_max stats_null_count stats_distinct_count stats_min_value stats_max_value compression                  encodings index_page_offset
1 a.parquet            0                  2                     1             100         0         108          2           col1 DOUBLE       1.0       2.0                0                   NA             1.0             2.0      SNAPPY PLAIN, RLE, RLE_DICTIONARY                NA
  dictionary_page_offset data_page_offset total_compressed_size total_uncompressed_size
1                      4               36                   104                     100
```

**Comment by krlmlr** [comment] 2024-04-24 06:47
Thanks. This looks like a duplicate of #137, we need to support the `MAP()` type in R to fix this.

**Closed by krlmlr** 2024-04-24 06:47 UTC

**Comment by krlmlr** [comment] 2024-04-24 07:21
Now in #61.
