### ISSUE TITLE
GitHub release?

### ISSUE THREAD

**Issue by eitsupi** [duckdb/duckdb-r#615] opened 2024-11-27 12:38 UTC
It seems that 1.1.3 does not have a GitHub release.

**Comment by kent37** [comment] 2024-12-03 16:37
Possibly the cause of #623 and #624?

**Comment by krlmlr** [comment] 2024-12-04 13:15
Thanks for reporting. Fixed by https://github.com/cynkra/fledge/pull/848 . I will trigger later today, or it will auto-run tomorrow.

**Comment by eitsupi** [comment] 2024-12-05 16:00
Hm, was that really fixed?

**Comment by krlmlr** [comment] 2024-12-05 18:48
Next try.

**Comment by krlmlr** [comment] 2024-12-07 15:35
Good now.

**Closed by krlmlr** 2024-12-07 15:35 UTC
