### ISSUE TITLE
``histogram(arg)`` aggregate function  not working in R

### ISSUE THREAD

**Issue by nassuphis** [duckdb/duckdb-r#62] opened 2024-01-04 12:17 UTC
OS OSX
DDB version 0.9.2-1

```
> tbl(con,sql("SELECT * FROM range(100) AS tt(x)")) %>%
+ summarise(h=sql("histogram(x)"))
Error in `collect()`:
! Failed to collect lazy table.
Caused by error:
! rapi_prepare: Unknown column type for prepare: MAP(BIGINT, UBIGINT)
Run `rlang::last_trace()` to see where the error occurred.
```

**Comment by krlmlr** [comment] 2024-03-03 18:55
Thanks. Duplicate of #61.

**Closed by krlmlr** 2024-03-03 18:55 UTC
